---
abstract: 'A simple module to extract the timestamp from media files in an flexible manner.'
author:
  - unknown
build_requires:
  DateTime::TimeZone: '0'
  File::Which: '0'
  Test::More: '0'
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Media-DateTime
provides:
  Media::DateTime:
    file: lib/Media/DateTime.pm
    version: '0.48'
  Media::DateTime::JPEG:
    file: lib/Media/DateTime/JPEG.pm
    version: '0.48'
requires:
  Carp: '0'
  DateTime: '0'
  Hash::Util: '0.05'
  Image::ExifTool: '0'
  Module::Pluggable: '0'
  Try::Tiny: '0'
  perl: '5.008'
resources:
  bugtracker: http://github.com/mvgrimes/media-datetime/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/mvgrimes/media-datetime
version: '0.48'
