---
name: Media-DateTime
version: 0.43
author:
  - 'Mark V. Grimes, E<lt>mgrimes@cpan.org<gt>'
abstract: |-
  An highly extensible module to extract the creation
  date and time from a file.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  DateTime: 0
  Hash::Util: 0.05
  Image::ExifTool: 0
  Module::Pluggable: 0
  perl: 5.008
build_requires:
  DateTime::TimeZone: 0
  File::Which: 0
  Test::More: 0
provides:
  Media::DateTime:
    file: lib/Media/DateTime.pm
    version: 0.43
  Media::DateTime::JPEG:
    file: lib/Media/DateTime/JPEG.pm
    version: 0.30
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
